### ISSUE TITLE
Dependency issue with tk on Debian

### ISSUE THREAD

**Issue by MichiK** [NoMoKeTo/c3nav#21]
When starting `main.py` or `configure.py` on my Debian machine at home, i got the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 39, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "configure.py", line 9, in <module>
    from classes import Graph, Node, Position
  File "/home/m/git/c3nav/src/classes/__init__.py", line 1, in <module>
    from .graph import Graph
  File "/home/m/git/c3nav/src/classes/graph.py", line 15, in <module>
    from .wifilocator import WifiLocator
  File "/home/m/git/c3nav/src/classes/wifilocator.py", line 5, in <module>
    from matplotlib import pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/lib/python3/dist-packages/matplotlib/externals/six.py", line 90, in __get__
    result = self._resolve()
  File "/usr/lib/python3/dist-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 41, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
```

Installing `python3-tk` by hand solved this. Probably this should be in `README.md` or so as there seems to be no possibility to put this in `requirements.txt`.

**Comment by codingcatgirl** [comment]
It is already stated in die `README.md`:

> (if this fails because of build dependencies use apt-get build-dep python-pil python-matplotlib python-scipy or something similar for you distribution to install the dependencies and run pip again)

**Comment by MichiK** [comment]
That's a different issue though:

```
apt-get build-dep python-pil python-matplotlib python-scipy
Reading package lists... Done
Building dependency tree
Reading state information... Done
Picking 'pillow' as source package instead of 'python-pil'
Picking 'matplotlib' as source package instead of 'python-matplotlib'
python-cairocffi is already the newest version (0.7.2-1).
python-cairocffi set to manually installed.
The following packages have unmet dependencies:
 python-cairocffi : Depends: python-cffi but it is not going to be installed
E: Build-dependencies for matplotlib could not be satisfied.
```
